version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "AC Version"
description: "Detecting DWG files version number into your browser...!"
url: "http://behrooz-tahanzadeh.github.io/ac-version/"
date: "January 2014"
googleAnalyticsCode: "UA-40560087-5"
